USE [AdventureWorksDW2019];
GO
SELECT [ProductKey]
      ,[ProductAlternateKey] as [ProductItemCode]
      --,[ProductSubcategoryKey]
      --,[WeightUnitMeasureCode]
      --,[SizeUnitMeasureCode]
      ,[EnglishProductName] as [ProductName]
	  ,ps.EnglishProductSubcategoryName as [SubCategory]
	  ,pc.EnglishProductCategoryName as [Category]
      --,[SpanishProductName]
      --,[FrenchProductName]
      --,[StandardCost]
      --,[FinishedGoodsFlag]
      ,[Color]
      --,[SafetyStockLevel]
      --,[ReorderPoint]
      --,[ListPrice]
      ,[Size]
      --,[SizeRange]
      --,[Weight]
      --,[DaysToManufacture]
      ,[ProductLine]
      --,[DealerPrice]
      --,[Class]
      --,[Style]
      ,[ModelName]
      --,[LargePhoto]
      ,[EnglishDescription] as [ProductDes]
      --,[FrenchDescription]
      --,[ChineseDescription]
      --,[ArabicDescription]
      --,[HebrewDescription]
      --,[ThaiDescription]
      --,[GermanDescription]
      --,[JapaneseDescription]
      --,[TurkishDescription]
      ,[StartDate]
      --,[EndDate]
      ,isnull (p.Status, 'Outdated') as [Status]
  FROM 
	DimProduct as p
	join DimProductSubCategory as ps on p.ProductSubcategoryKey = ps.ProductSubcategoryKey
	join DimProductCategory as pc on ps.ProductCategoryKey = pc.ProductCategoryKey
